version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

  phpserver:
    image: php:fpm-alpine
    volumes:
      - ./:/var/www
